apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mern-devops
namePrefix: prod-

resources:
  - ../../base

patches:
  - path: backend-patch.yml
  - path: frontend-patch.yml
  # - path: ingress-patch.yml     # uncomment if using ingress

configMapGenerator:
  - name: backend-config
    literals:
      - PORT=8000
      - mongoDBURL=mongodb://admin:password123@prod-mongodb-service:27017/db?authSource=admin